### ISSUE TITLE
NPM packages install fails

### ISSUE THREAD

**Issue by bampakoa** [stevermeister/ngWig#166]
`npm install` fails with the following message:

```
Downloading http://phantomjs.googlecode.com/files/phantomjs-1.9.2-linux-x86_64.tar.bz2
Saving to /tmp/phantomjs/phantomjs-1.9.2-linux-x86_64.tar.bz2
Receiving...
Error requesting archive
Phantom installation failed Error: Error with http request: { 'content-type': 'text/html; charset=UTF-8',
  'content-length': '1603',
  date: 'Tue, 07 Mar 2017 20:05:40 GMT',
  connection: 'close' }
    at ClientRequest.<anonymous> (ngWig/node_modules/phantomjs/install.js:227:23)
    at ClientRequest.g (events.js:291:16)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:474:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
    at Socket.socketOnData (_http_client.js:363:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18) Error: Error with http request: { 'content-type': 'text/html; charset=UTF-8','content-length': '1603',
  date: 'Tue, 07 Mar 2017 20:05:40 GMT',
  connection: 'close' }
    at ClientRequest.<anonymous> (ngWig/node_modules/phantomjs/install.js:227:23)
    at ClientRequest.g (events.js:291:16)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:474:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
    at Socket.socketOnData (_http_client.js:363:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)


```

After some digging I found out that **grunticon** package is responsible for the error message. Another user has already reported something relevant [here](https://github.com/filamentgroup/grunticon/issues/334).

@stevermeister I tried with the latest version of the package and the problem seems to vanish, but I cannot know other complications that may have. Can you confirm?

**Comment by stevermeister** [comment]
same error here

**Comment by stevermeister** [comment]
update grunticon also works for me, made a hotfix for it
